export const US_STATES = [
  { code: "US", labelKo: "미국 전체" },
  { code: "AL", labelKo: "앨라배마" },
  { code: "AK", labelKo: "알래스카" },
  { code: "AZ", labelKo: "애리조나" },
  { code: "AR", labelKo: "아칸소" },
  { code: "CA", labelKo: "캘리포니아" },
  { code: "CO", labelKo: "콜로라도" },
  { code: "CT", labelKo: "코네티컷" },
  { code: "DE", labelKo: "델라웨어" },
  { code: "FL", labelKo: "플로리다" },
  { code: "GA", labelKo: "조지아" },
  { code: "HI", labelKo: "하와이" },
  { code: "ID", labelKo: "아이다호" },
  { code: "IL", labelKo: "일리노이" },
  { code: "IN", labelKo: "인디애나" },
  { code: "IA", labelKo: "아이오와" },
  { code: "KS", labelKo: "캔자스" },
  { code: "KY", labelKo: "켄터키" },
  { code: "LA", labelKo: "루이지애나" },
  { code: "ME", labelKo: "메인" },
  { code: "MD", labelKo: "메릴랜드" },
  { code: "MA", labelKo: "매사추세츠" },
  { code: "MI", labelKo: "미시간" },
  { code: "MN", labelKo: "미네소타" },
  { code: "MS", labelKo: "미시시피" },
  { code: "MO", labelKo: "미주리" },
  { code: "MT", labelKo: "몬태나" },
  { code: "NE", labelKo: "네브래스카" },
  { code: "NV", labelKo: "네바다" },
  { code: "NH", labelKo: "뉴햄프셔" },
  { code: "NJ", labelKo: "뉴저지" },
  { code: "NM", labelKo: "뉴멕시코" },
  { code: "NY", labelKo: "뉴욕" },
  { code: "NC", labelKo: "노스캐롤라이나" },
  { code: "ND", labelKo: "노스다코타" },
  { code: "OH", labelKo: "오하이오" },
  { code: "OK", labelKo: "오클라호마" },
  { code: "OR", labelKo: "오리건" },
  { code: "PA", labelKo: "펜실베이니아" },
  { code: "RI", labelKo: "로드아일랜드" },
  { code: "SC", labelKo: "사우스캐롤라이나" },
  { code: "SD", labelKo: "사우스다코타" },
  { code: "TN", labelKo: "테네시" },
  { code: "TX", labelKo: "텍사스" },
  { code: "UT", labelKo: "유타" },
  { code: "VT", labelKo: "버몬트" },
  { code: "VA", labelKo: "버지니아" },
  { code: "WA", labelKo: "워싱턴" },
  { code: "WV", labelKo: "웨스트버지니아" },
  { code: "WI", labelKo: "위스콘신" },
  { code: "WY", labelKo: "와이오밍" },
  { code: "DC", labelKo: "워싱턴 D.C." },
];

export const getStateLabel = (stateCode: string): string => {
  return US_STATES.find((state) => state.code === stateCode)?.labelKo ?? stateCode;
};
